### PR TITLE
added loader to select input

### PR DESCRIPTION
**Pull request by to-sh-1**

### CODE REVIEW

**Comment by to-sh-1** [comment]
Added loader next to label in select input

**Comment by inkblotty** [comment]
This looks great, but we need url-loader and that process updated in webpack to be able to bundle svgs. @JacobCooley

**Review by inkblotty — CHANGES_REQUESTED** [review]
Webpack svg loader needed for proper bundling.

**Review by inkblotty — APPROVED** [review]
Webpack on master updated to bundle images. Approved 👍

**Pull request merged**
